FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY ../../go.* .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/weather-service

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/main /main
EXPOSE 8000
ENTRYPOINT ["/main"]
